### ISSUE TITLE
Cannot find file: /home/mm/Projektek/qt/openhmitester/testbench/desktop/desktop.pro

### ISSUE THREAD

**Issue by martonmiklos** [pedromateo/openhmitester#1]
Hello,

I have tried to compile the project under Ubuntu 14.04.3 with Qt 5.2.1 by running qmake build_all.pro

I got the following error.

make[1]: Leaving directory `/home/mm/Projektek/qt/openhmitester/qt_linux_lib_preload'
cd testbench/desktop/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/mm/Projektek/qt/openhmitester/testbench/desktop/desktop.pro -o Makefile ) && make -f Makefile 
Cannot find file: /home/mm/Projektek/qt/openhmitester/testbench/desktop/desktop.pro.

Workaround: rename  simusaes.pro to desktop.pro

**Comment by martonmiklos** [comment]
Same applies to the testbench/web/web.pro file.

**Comment by pedromateo** [comment]
build_all.pro uses ".file" variable to allow different names in pro files:

SUBDIRS += hmi_tester
SUBDIRS += lib_preload
SUBDIRS += qt_linux_hmi_tester
SUBDIRS += qt_linux_lib_preload
SUBDIRS += testbench/desktop
testbench/desktop.file = testbench/desktop/simusaes.pro
SUBDIRS += testbench/web
testbench/web.file = testbench/web/fancybrowser.pro

People is not experiencing problems doing this. Did you tried with other version of Qt? I am now compiling with Qt4.8 and Qt5.5, and both work fine.
