### ISSUE TITLE
Support for embedded PyQt? 

### ISSUE THREAD

**Issue by OleksiyPuzikov** [pedromateo/openhmitester#11]
So, I've embedded a simple python script into a Qt application. OHT does launch application but doesn't show the window; when launched outside OHT, window shows up successfully.

C++ Qt Code (main.cpp):

``` cpp

#include <QApplication>
#include <Python.h>

int main(int argc, char *argv[]) {

  Py_SetProgramName(argv[0]);
  Py_Initialize();
  QApplication a(argc, argv);

  FILE *f = fopen("test.py", "r");
  PyRun_SimpleFile(f, "test.py");

  a.exec();

  fclose(f);
  Py_Finalize();
  return 0;
}

```

Complete PyQt Code (test.py):

``` python
from PyQt5 import QtWidgets
w = QtWidgets.QMainWindow()
w.show()

```

**Comment by pedromateo** [comment]
Sorry for the delay in my answer.
I have never used OHT with Python. Anyway, at least, the application should be launched.
If you provide me with more information (e.g., standard and log outputs), maybe I can help you.
